x-common-env: &common_env
  PUID: ${PUID}
  PGID: ${PGID}
  TZ: ${TZ}

x-common-service: &common_service
  networks:
    - homelab_network
  restart: unless-stopped
  extra_hosts:
    - "authentik.${SERVER_DOMAIN}:${SERVER_IP}"

x-healthcheck-defaults: &healthcheck_defaults
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 30s

x-watchtower-auto-update: &auto_update
  com.centurylinklabs.watchtower.enable: "true"
  com.centurylinklabs.watchtower.cooldown-delay: "24h"

x-watchtower-monitor-only: &monitor_updates_only
  com.centurylinklabs.watchtower.enable: "true"
  com.centurylinklabs.watchtower.monitor-only: "true"

x-watchtower-pinned: &pinned_version
  com.centurylinklabs.watchtower.enable: "false"

name: homelab-applications
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1
    container_name: homepage
    mac_address: "06:01:01:00:00:00"
    <<: *common_service
    labels:
      <<: *auto_update
    environment:
      <<: *common_env
      HOMEPAGE_ALLOWED_HOSTS: ${SERVER_IP}:${HOMEPAGE_PORT},home.${SERVER_DOMAIN},homepage:3000
    ports:
      - ${HOMEPAGE_PORT}:3000
    volumes:
      - ${CONFIG_ROOT}/homepage/config:/app/config
      - ${NAS}:${NAS}
      - /var/run/docker.sock:/var/run/docker.sock:ro

  immich-server:
    image: ghcr.io/immich-app/immich-server:v3
    container_name: immich-server
    mac_address: "06:02:01:00:00:00"
    <<: *common_service
    labels:
      <<: *pinned_version
    depends_on:
      - immich-redis
      - immich-postgres
    environment:
      <<: *common_env
      DB_HOSTNAME: immich-postgres
      DB_DATABASE_NAME: immich
      DB_USERNAME: immich
      DB_PASSWORD: immich
      REDIS_HOSTNAME: immich-redis
      IMMICH_TELEMETRY_INCLUDE: all
    ports:
      - ${IMMICH_SERVER_PORT}:2283
    volumes:
      - ${CONFIG_ROOT}/immich-server/data:/data
      - /etc/localtime:/etc/localtime:ro

  immich-ml:
    image: ghcr.io/immich-app/immich-machine-learning:v3
    container_name: immich-ml
    mac_address: "06:02:02:00:00:00"
    <<: *common_service
    labels:
      <<: *pinned_version
    environment:
      <<: *common_env
    volumes:
      - ${CONFIG_ROOT}/immich-ml/cache:/cache

  immich-postgres:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    container_name: immich-postgres
    mac_address: "06:02:03:00:00:00"
    <<: *common_service
    labels:
      <<: *pinned_version
    environment:
      <<: *common_env
      POSTGRES_DB: immich
      POSTGRES_USER: immich
      POSTGRES_PASSWORD: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    shm_size: 128m
    volumes:
      - ${CONFIG_ROOT}/immich-postgres/data:/var/lib/postgresql/data

  immich-postgres-exporter:
    image: ghcr.io/prometheus-community/postgres-exporter:v0
    container_name: immich-postgres-exporter
    mac_address: "06:02:03:01:00:00"
    <<: *common_service
    labels:
      <<: *auto_update
    depends_on:
      - immich-postgres
    environment:
      DATA_SOURCE_NAME: "postgresql://immich:immich@immich-postgres:5432/immich?sslmode=disable"

  immich-redis:
    image: docker.io/valkey/valkey:9@sha256:3acc0687f2a2e1091fae6450d7842dd658c941338cf0a873ddd9e14b9e4ea4dd
    container_name: immich-redis
    mac_address: "06:02:04:00:00:00"
    <<: *common_service
    labels:
      <<: *pinned_version
    environment:
      <<: *common_env
    healthcheck:
      test: redis-cli ping || exit 1

  immich-redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: immich-redis-exporter
    mac_address: "06:02:04:01:00:00"
    <<: *common_service
    labels:
      <<: *auto_update
    depends_on:
      - immich-redis
    environment:
      REDIS_ADDR: "redis://immich-redis:6379"

  syncthing:
    image: lscr.io/linuxserver/syncthing:2.1.3
    container_name: syncthing
    mac_address: "06:03:01:00:00:00"
    <<: *common_service
    labels:
      <<: *pinned_version
    environment:
      <<: *common_env
    healthcheck:
      <<: *healthcheck_defaults
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8384/rest/noauth/health"]
    ports:
      - ${SYNCTHING_PORT_UI}:8384
      - ${SYNCTHING_PORT_TRAFFIC}:22000
      - ${SYNCTHING_PORT_TRAFFIC}:22000/udp
      - ${SYNCTHING_PORT_DISCOVERY}:21027/udp
    volumes:
      - ${CONFIG_ROOT}/syncthing/config:/config

  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:v0
    container_name: zerobyte
    mac_address: "06:04:01:00:00:00"
    <<: *common_service
    labels:
      <<: *auto_update
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      <<: *common_env
      APP_SECRET: ${ZEROBYTE_SECRET}
      BASE_URL: http://${SERVER_IP}:${ZEROBYTE_PORT}
      TRUSTED_ORIGINS: https://zerobyte.${SERVER_DOMAIN}
      ENABLE_DEV_PANEL: true
      LOG_LEVEL: debug
    healthcheck:
      <<: *healthcheck_defaults
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:4096"]
    ports:
      - ${ZEROBYTE_PORT}:4096
    volumes:
      - ${CONFIG_ROOT}/zerobyte/data:/var/lib/zerobyte
      - ${NAS}:${NAS}
      - ${APPS}:${APPS}
      - /etc/localtime:/etc/localtime:ro

networks:
  homelab_network:
    external: true
