x-common-env: &common_env
  PUID: ${PUID}
  PGID: ${PGID}
  TZ: ${TZ}

x-common-service: &common_service
  networks:
    - homelab_network
  restart: unless-stopped

x-auto-update: &auto_update
  labels:
    wud.tag.include: docker.update

x-no-update: &no_update
  labels:
    wud.tag.exclude: docker.update

name: homelab-applications
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    <<: [*common_service, *auto_update]
    hostname: gitlab.${SERVER_DOMAIN}
    environment:
      <<: *common_env
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.${SERVER_DOMAIN}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_PORT_SSH}
    ports:
      - ${GITLAB_PORT_WEB}:80
      - ${GITLAB_PORT_SSH}:22
    volumes:
      - ${CONFIG_ROOT}/gitlab/config:/etc/gitlab
      - ${CONFIG_ROOT}/gitlab/logs:/var/log/gitlab
      - ${CONFIG_ROOT}/gitlab/data:/var/opt/gitlab
    deploy:
      resources:
        limits:
          cpus: "6.0"
          memory: "12G"
    shm_size: '256m'

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    <<: [*common_service, *auto_update]
    environment:
      <<: *common_env
      HOMEPAGE_ALLOWED_HOSTS: ${SERVER_IP}:${HOMEPAGE_PORT},home.${SERVER_DOMAIN}
    ports:
      - ${HOMEPAGE_PORT}:3000
    volumes:
      - ${CONFIG_ROOT}/homepage/config:/app/config
      - ${NAS}:${NAS}
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "256M"

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    <<: [*common_service, *auto_update]
    environment:
      <<: *common_env
    ports:
      - ${SYNCTHING_PORT_UI}:8384
      - ${SYNCTHING_PORT_TRAFFIC}:22000
      - ${SYNCTHING_PORT_TRAFFIC}:22000/udp
      - ${SYNCTHING_PORT_DISCOVERY}:21027/udp
    volumes:
      - ${CONFIG_ROOT}/syncthing/config:/config
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "128M"

  vaultwarden:
    image: vaultwarden/server:latest
    <<: [*common_service, *auto_update]
    environment:
      <<: *common_env
    ports:
      - ${VAULTWARDEN_PORT}:80
    volumes:
      - ${CONFIG_ROOT}/vaultwarden/data:/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "128M"

  wud:
    image: getwud/wud
    <<: [*common_service, *auto_update]
    environment:
      <<: *common_env
      WUD_TRIGGER_DOCKER_UPDATE_AUTO: true
      WUD_TRIGGER_DOCKER_UPDATE_PRUNE: true
      WUD_WATCHER_DOCKER_CRON: 0 3 * * *
      WUD_REGISTRY_LSCR_PUBLIC_USERNAME: ${WUD_LSCR_USERNAME}
      WUD_REGISTRY_LSCR_PUBLIC_TOKEN: ${WUD_LSCR_TOKEN}
    ports:
      - ${WUD_PORT}:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"

  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:latest
    <<: [*common_service, *auto_update]
    privileged: true
    environment:
      <<: *common_env
      APP_SECRET: ${ZEROBYTE_SECRET}
      BASE_URL: http://${SERVER_IP}:${ZEROBYTE_PORT}
      TRUSTED_ORIGINS: https://zerobyte.${SERVER_DOMAIN}
      ENABLE_DEV_PANEL: true
      LOG_LEVEL: debug
    ports:
      - ${ZEROBYTE_PORT}:4096
    volumes:
      - ${CONFIG_ROOT}/zerobyte/data:/var/lib/zerobyte
      - ${NAS}:${NAS}
      - ${APPS}:${APPS}
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "2G"

networks:
  homelab_network:
    external: true
