x-common-env: &common_env
  PUID: ${PUID}
  PGID: ${PGID}
  TZ: ${TZ}

x-common-service: &common_service
  networks:
    - homelab_network
  restart: unless-stopped
  extra_hosts:
    - "authentik.${SERVER_DOMAIN}:${SERVER_IP}"

x-watchtower-auto-update: &auto_update
  com.centurylinklabs.watchtower.enable: "true"
  com.centurylinklabs.watchtower.cooldown-delay: "24h"

x-watchtower-monitor-only: &monitor_updates_only
  com.centurylinklabs.watchtower.enable: "true"
  com.centurylinklabs.watchtower.monitor-only: "true"

x-watchtower-pinned: &pinned_version
  com.centurylinklabs.watchtower.enable: "false"

name: homelab-applications
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1
    labels:
      <<: *auto_update
    <<: *common_service
    environment:
      <<: *common_env
      HOMEPAGE_ALLOWED_HOSTS: ${SERVER_IP}:${HOMEPAGE_PORT},home.${SERVER_DOMAIN}
    ports:
      - ${HOMEPAGE_PORT}:3000
    volumes:
      - ${CONFIG_ROOT}/homepage/config:/app/config
      - ${NAS}:${NAS}
      - /var/run/docker.sock:/var/run/docker.sock:ro

  immich:
    image: ghcr.io/immich-app/immich-server:v3
    labels:
      <<: *pinned_version
    <<: *common_service
    environment:
      <<: *common_env
      DB_HOSTNAME: immich-postgres
      DB_DATABASE_NAME: immich
      DB_USERNAME: immich
      DB_PASSWORD: immich
      REDIS_HOSTNAME: immich-redis
    ports:
      - ${IMMICH_PORT}:2283
    volumes:
      - ${CONFIG_ROOT}/immich-server/data:/data
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - immich-redis
      - immich-postgres

  immich-ml:
    image: ghcr.io/immich-app/immich-machine-learning:v3
    labels:
      <<: *pinned_version
    <<: *common_service
    environment:
      <<: *common_env
    volumes:
      - ${CONFIG_ROOT}/immich-ml/cache:/cache

  immich-postgres:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    labels:
      <<: *pinned_version
    <<: *common_service
    environment:
      <<: *common_env
      POSTGRES_DB: immich
      POSTGRES_USER: immich
      POSTGRES_PASSWORD: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${CONFIG_ROOT}/immich-postgres/data:/var/lib/postgresql/data
    shm_size: 128m

  immich-redis:
    image: docker.io/valkey/valkey:9@sha256:3acc0687f2a2e1091fae6450d7842dd658c941338cf0a873ddd9e14b9e4ea4dd
    labels:
      <<: *pinned_version
    <<: *common_service
    environment:
      <<: *common_env
    healthcheck:
      test: redis-cli ping || exit 1

  pacoloco:
    image: ghcr.io/anatol/pacoloco:latest
    labels:
      <<: *auto_update
    <<: *common_service
    environment:
      <<: *common_env
    user: "${PUID}:${PGID}"
    ports:
      - ${PACOLOCO_PORT}:9129
    volumes:
      - ${CONFIG_ROOT}/pacoloco/cache:/var/cache/pacoloco
      - ${CONFIG_ROOT}/pacoloco/config/pacoloco.yaml:/etc/pacoloco.yaml

  syncthing:
    image: lscr.io/linuxserver/syncthing:2.1.3
    labels:
      <<: *pinned_version
    <<: *common_service
    environment:
      <<: *common_env
    ports:
      - ${SYNCTHING_PORT_UI}:8384
      - ${SYNCTHING_PORT_TRAFFIC}:22000
      - ${SYNCTHING_PORT_TRAFFIC}:22000/udp
      - ${SYNCTHING_PORT_DISCOVERY}:21027/udp
    volumes:
      - ${CONFIG_ROOT}/syncthing/config:/config

  watchtower:
    image: ghcr.io/nicholas-fedor/watchtower:1
    labels:
      <<: *pinned_version
    <<: *common_service
    environment:
      <<: *common_env
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: "86400"
      # TODO - RSS feed
      WATCHTOWER_NOTIFICATIONS: "shoutrrr"
      WATCHTOWER_NOTIFICATION_URL: "discord://TOKEN@WEBHOOKID"
      WATCHTOWER_NOTIFICATIONS_LEVEL: "info"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:v0
    labels:
      <<: *auto_update
    <<: *common_service
    privileged: true
    environment:
      <<: *common_env
      APP_SECRET: ${ZEROBYTE_SECRET}
      BASE_URL: http://${SERVER_IP}:${ZEROBYTE_PORT}
      TRUSTED_ORIGINS: https://zerobyte.${SERVER_DOMAIN}
      ENABLE_DEV_PANEL: true
      LOG_LEVEL: debug
    ports:
      - ${ZEROBYTE_PORT}:4096
    volumes:
      - ${CONFIG_ROOT}/zerobyte/data:/var/lib/zerobyte
      - ${NAS}:${NAS}
      - ${APPS}:${APPS}
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN

networks:
  homelab_network:
    external: true
