x-common-env: &common_env
  PUID: ${PUID}
  PGID: ${PGID}
  TZ: ${TZ}

x-common-service: &common_service
  networks:
    - homelab_network
  restart: unless-stopped
  extra_hosts:
    - "authentik.${SERVER_DOMAIN}:${SERVER_IP}"

x-watchtower-auto-update: &auto_update
  com.centurylinklabs.watchtower.enable: "true"
  com.centurylinklabs.watchtower.cooldown-delay: "24h"

x-watchtower-monitor-only: &monitor_updates_only
  com.centurylinklabs.watchtower.enable: "true"
  com.centurylinklabs.watchtower.monitor-only: "true"

x-watchtower-pinned: &pinned_version
  com.centurylinklabs.watchtower.enable: "false"

name: homelab-authentication
services:
  authentik-server:
    image: ghcr.io/goauthentik/server:2026.5
    mac_address: "0A:01:01:00:00:00"
    labels:
      <<: *pinned_version
    <<: *common_service
    command: server
    depends_on:
      authentik-postgresql:
        condition: service_healthy
    env_file:
      - .env
    environment:
      <<: *common_env
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: authentik
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    ports:
      - ${AUTHENTIK_PORT_HTTP}:9000
      - ${AUTHENTIK_PORT_HTTPS}:9443
    shm_size: 512mb
    volumes:
      - ${CONFIG_ROOT}/authentik-server/data:/data
      - ${CONFIG_ROOT}/authentik-server/custom-templates:/templates

  authentik-worker:
    image: ghcr.io/goauthentik/server:2026.5
    mac_address: "0A:01:02:00:00:00"
    labels:
      <<: *pinned_version
    <<: *common_service
    command: worker
    depends_on:
      authentik-postgresql:
        condition: service_healthy
    env_file:
    - .env
    environment:
      <<: *common_env
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: authentik
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    shm_size: 512mb
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_ROOT}/authentik-worker/data:/data
      - ${CONFIG_ROOT}/authentik-worker/certs:/certs
      - ${CONFIG_ROOT}/authentik-worker/custom-templates:/templates

  authentik-postgresql:
    image: docker.io/library/postgres:16-alpine
    mac_address: "0A:01:03:00:00:00"
    labels:
      <<: *pinned_version
    <<: *common_service
    env_file:
      - .env
    environment:
      <<: *common_env
      POSTGRES_DB: authentik
      POSTGRES_PASSWORD: authentik
      POSTGRES_USER: authentik
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
      - CMD-SHELL
      - pg_isready -d authentik -U authentik
      timeout: 5s
    volumes:
      - ${CONFIG_ROOT}/authentik-postgres/data:/var/lib/postgresql/data

  vaultwarden:
    image: vaultwarden/server:1.37.1
    mac_address: "0A:02:01:00:00:00"
    labels:
      <<: *pinned_version
    <<: *common_service
    environment:
      <<: *common_env
    ports:
      - ${VAULTWARDEN_PORT}:80
    volumes:
      - ${CONFIG_ROOT}/vaultwarden/data:/data

networks:
  homelab_network:
    external: true
