x-common-env: &common_env
  PUID: ${PUID}
  PGID: ${PGID}
  TZ: ${TZ}

x-common-service: &common_service
  networks:
    - homelab_network
  restart: unless-stopped
  extra_hosts:
    - "authentik.${SERVER_DOMAIN}:${SERVER_IP}"

name: homelab-logging
services:
  grafana:
    image: grafana/grafana:latest
    <<: *common_service
    environment:
      <<: *common_env
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "authentik"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "fSrraNAb6yjx7LChfVnDo9dcP3CXr1pPX9gGKrBo"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ${GRAFANA_AUTH_SECRET}
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://authentik.${SERVER_DOMAIN}/application/o/authorize/"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "http://authentik-server:9000/application/o/token/"
      GF_AUTH_GENERIC_OAUTH_API_URL: "http://authentik-server:9000/application/o/userinfo/"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://authentik.${SERVER_DOMAIN}/application/o/grafana/end-session/"
      GF_AUTH_OAUTH_AUTO_LOGIN: "true"
      GF_SERVER_ROOT_URL: "https://grafana.${SERVER_DOMAIN}"
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - ${CONFIG_ROOT}/grafana/data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    <<: *common_service
    environment:
      <<: *common_env
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - ${CONFIG_ROOT}/prometheus/data:/prometheus
      - ${CONFIG_ROOT}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-admin-api"
      - "--storage.tsdb.retention.time=90d"
      - "--storage.tsdb.retention.size=15GB"
      - "--storage.tsdb.wal-compression"

  scrutiny:
    image: ghcr.io/analogj/scrutiny:latest-omnibus
    <<: *common_service
    environment:
      <<: *common_env
    ports:
      - ${SCRUTINY_PORT_UI}:8080
      - ${SCRUTINY_PORT_DB}:8086
    volumes:
      - ${CONFIG_ROOT}/scrutiny/config:/config
      - ${CONFIG_ROOT}/scrutiny/influxdb:/opt/scrutiny/influxdb
      - /run/udev:/run/udev:ro
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/nvme0n1:/dev/nvme0n1
      - /dev/nvme1n1:/dev/nvme1n1
    cap_add:
      - SYS_RAWIO

  uptime-kuma:
    image: louislam/uptime-kuma:2
    <<: *common_service
    environment:
      <<: *common_env
    ports:
      - ${UPTIME_KUMA_PORT}:3001
    volumes:
      - ${CONFIG_ROOT}/uptime-kuma/data:/app/data

networks:
  homelab_network:
    external: true
